### ISSUE TITLE
dfind improvements

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/COMDIRAC#3]
I've just started playing with this, and I find it very very exciting. The dfind command in particular is exactly the kind of interface that some users want to use. I have 1 comment though: it would be nice that the print out does not include the query nor the time it took, as then it can be used to pipe into a text file and used as input for job submission for example. Otherwise, the first line contains   ESC[?1034hQuery: {'ProdID': 1500}
and the last line is QueryTime 0.05 sec

Thanks!

**Comment by pigay** [comment]
Hi Stephane,

Thank you for your comments.

For dfind output, you are right. I was just using "do_find" method from FileCatalogClientCLI, so dfind has the same behaviour.

I may reimplement this method in "dfind", but it's quite long and I don't like much code duplication. Or should we just remove annoying output from FileCatalogClientCLI instead?

Pierre

**Comment by sposs** [comment]
Well, I guess Andrei would have to say something about that. Maybe the print out could be left as a cli option, like a verbose switch...

**Comment by sposs** [comment]
In fact, I think it would be best to use findFilesByMetadata directly instead of passing through the CLI call..

**Comment by pigay** [comment]
You're maybe right. But I'm so lazy ;)

I'll try to do ti as soon as I get some time.

Pierre

**Comment by sposs** [comment]
I'm looking at this right now and I think that to get it right, the method __createQuery of the FliCatalogCLI should be made available to the outside, so that you can call it in your code. This is for Andrei I suppose...

**Comment by pigay** [comment]
Yes, he told me that he wanted to gather some of the features of FileCatalogClientClI somewhere under Interfaces/Utilities/ so they could be shared between different clients.

I'll wait until he commits his changes. After that, using findFilesByMetadata should after __createQuyery should be straightforward.

**Comment by pigay** [comment]
Following Andreï advice, I wrote a [RFC](https://github.com/DIRACGrid/DIRAC/wiki/Gathering-some-reusable-functions-in-a-utilities-package-%28RFC%29) in DIRAC itself.

if it is accepted, I'll be able to better control `dfind` output.

**Comment by pigay** [comment]
I finally changed my mind (no answers in the RFC).

I added a `-q` option to `do_find()` filecatalog-cli (https://github.com/DIRACGrid/DIRAC/pull/1657 to appear in DIRAC v7r0) which I may use by default in COMDIRAC `dfind`.

It may be possible to import this commit in DIRAC rel-v6r8 or rel-v6r9 if you wish.

**Comment by pigay** [comment]
Available in COMDIRAC v0r9 (needs DIRAC v6r11)
