### ISSUE TITLE
new command "dproxy"

### ISSUE THREAD

**Issue by bregeon** [DIRACGrid/COMDIRAC#67]
Hello,
I just noticed that I have a setup script with an alias to create my Dirac proxy
`alias proxy='dirac-proxy-init -g cta_prod -M'`

There could probably be a `dproxy` command, where the default "Role" could be defined in the configuration file.
Cheers
Johan

**Comment by pigay** [comment]
Hi Johan,

Aren't you just looking for `dinit`?

Cheers,
Pierre

**Comment by bregeon** [comment]
ah, yes thanks, dinit looks good !
