### ISSUE TITLE
dcd without arguments does not change directory to the home directory

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/COMDIRAC#71]
dcd command given without arguments should change directory to the home directory as specified in the dconfig

**Comment by pigay** [comment]
Hi Andrei,

I don't reproduce the same behaviour with a fresh install. Can you tell me more?

Pierre

**Comment by atsareg** [comment]
False alert. Actually the problem was reported by a user who actually made a wrong configuration of the COMDIRAC session.
