### ISSUE TITLE
Add to conda-forge?

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/COMDIRAC#72]
As suggested in https://github.com/DIRACGrid/DIRAC/issues/4779#issuecomment-714417463.

The nicest solution is probably to add support for `pip install`-ing `COMDIRAC` by adding a `setup.py` ([example](https://github.com/pypa/sampleproject)). Making the conda-forge package is then easy.

**Comment by pigay** [comment]
@chrisburr  As far as I know, COMDIRAC was installed as a module of DIRAC. Do you mean it can be installed with its own `setup.py` specifying DIRAC as a dependency, or is there a way to somehow optionally include COMDIRAC within DIRAC's own `setup.py`?

**Comment by pigay** [comment]
@chrisburr @atsareg Honestly, I don't have a clue about how to install DIRAC itself with setup.py (or pip? conda?). Do you have any pointer?

**Comment by pigay** [comment]
Hi @chrisburr  I didn't manage to use conda to install DIRAC client. Do I need to configure any special channel? Can you tell me how?

**Comment by chrisburr** [comment]
Sorry this got lost in a mess of other GitHub notifications. The simplest thing is probably to wait for me to finish https://github.com/DIRACGrid/DIRAC/issues/4774 which when then make this much simplier.

I'll get back to you some time early next year.

**Comment by pigay** [comment]
Thanks, I will watch  https://github.com/DIRACGrid/DIRAC/issues/4774

**Comment by atsareg** [comment]
@TaykYoku has implemented the PyPi deployment
