### ISSUE TITLE
add dsize command

### ISSUE THREAD

**Issue by pigay** [DIRACGrid/COMDIRAC#73]
Copy `fc-cli size -l` functionality

**Comment by bregeon** [comment]
Merci Pierre :)

`FC:/> size -l /vo.cta.in2p3.fr/MC/PROD5/Paranal/gamma/
directory: /vo.cta.in2p3.fr/MC/PROD5/Paranal/gamma
Logical Size: 68,689,638,652,657 Files: 71991 Directories: 110

   StorageElement Size               Replicas
=============================================
 1 DESY-ZN-Disk    2,432,743,569,516     3799
 2 LANCASTER-Disk 31,028,230,932,339    22404
 3 CNAF-Disk         592,899,287,218      972
 4 LAPP-Disk      33,550,029,298,724    43937
 5 CEA-Disk            1,398,918,687      200
 6 CC-IN2P3-Disk   1,084,336,646,173      679
   Total          68,689,638,652,657    71991
----------------------------------------------
`
